### ISSUE TITLE
Fetch twitter profile pic

### ISSUE THREAD

**Issue by aswinzz** [NJACKWinterOfCode/Tweezy#3]
In the webapp the user pic should also be displayed.

**Comment by Sai-Adarsh** [comment]
I would like to take this up!

**Comment by aswinzz** [comment]
yeah sure you can work on this

**Comment by Sai-Adarsh** [comment]
> yeah sure you can work on this

where exactly should i display the profile pic

**Comment by Sai-Adarsh** [comment]
> > yeah sure you can work on this
> 
> where exactly should i display the profile pic

done with it, could you tell me where exactly should i display the profile pic
